# Copyright (c) 2026 Denys Nazarenko, Lviv Polytechnic National University.
"""Standard elliptic-curve domain parameters for DSTU 4145-2002.

This module bundles the recommended (named) curves of the standard. Each
:class:`Dstu4145DomainParameters` instance ties together:

* the underlying binary extension field :math:`GF(2^m)` (degree ``m`` and
  reduction polynomial),
* the curve coefficients ``a`` and ``b``,
* the cyclic subgroup order ``n``, and
* the base point :math:`P` (called ``base_point``).

These tuples are publicly defined in *DSTU 4145-2002, Annex B*. The
parameter set ``DSTU4145_M163_PB`` reproduces the example used in the test
appendix of the standard (and also in the reference implementations) so
that the signature primitive can be checked against a published vector.

Because the full set of named curves is large and our diploma project only
requires a working secure channel, we provide:

* ``DSTU4145_M163_PB`` --- the smallest standard curve, used in the worked
  examples of Annex B of the standard, and
* ``DSTU4145_M257_PB`` --- the most widely deployed curve in Ukrainian
  applications, which is what the secure channel uses by default.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

from secure_channel.crypto.binary_curve import BinaryCurvePoint, BinaryEllipticCurve
from secure_channel.crypto.binary_field import BinaryExtensionField


@dataclass(frozen=True, slots=True)
class Dstu4145DomainParameters:
    """Bundle of all values needed to instantiate a DSTU 4145-2002 system.

    :param curve: The elliptic curve over a binary extension field.
    :param subgroup_order: The (prime) order :math:`n` of the cyclic
        subgroup generated by :attr:`base_point`.
    :param base_point: The generator :math:`P` of the prime-order subgroup.
    """

    curve: BinaryEllipticCurve
    subgroup_order: int
    base_point: BinaryCurvePoint

    def __post_init__(self) -> None:
        if self.subgroup_order < 2:
            raise ValueError("Subgroup order must be a prime greater than one.")
        if self.base_point.curve != self.curve:
            raise ValueError("Base point does not belong to the supplied curve.")

    @property
    def field(self) -> BinaryExtensionField:
        """The underlying binary extension field."""
        return self.curve.field


# ---------------------------------------------------------------------------
# DSTU 4145 named curve over GF(2^163), trinomial basis x^163 + x^7 + x^6 + x^3 + 1
# ---------------------------------------------------------------------------

# DSTU 4145-2002 specifies a pentanomial reduction polynomial whose
# exponents (in addition to m and 0) are 7, 6 and 3. The constants below
# match the example parameter set used in Annex B of the standard.
_M163_REDUCTION_POLYNOMIAL: Final[int] = (
    (1 << 163) | (1 << 7) | (1 << 6) | (1 << 3) | 1
)
_M163_FIELD: Final[BinaryExtensionField] = BinaryExtensionField(
    degree=163,
    reduction_polynomial=_M163_REDUCTION_POLYNOMIAL,
)
_M163_CURVE: Final[BinaryEllipticCurve] = BinaryEllipticCurve(
    field=_M163_FIELD,
    coefficient_a=1,
    coefficient_b=0x5FF6108462A2DC8210AB403925E638A19C1455D21,
)

DSTU4145_M163_PB: Final[Dstu4145DomainParameters] = Dstu4145DomainParameters(
    curve=_M163_CURVE,
    subgroup_order=0x400000000000000000002BEC12BE2262D39BCF14D,
    base_point=_M163_CURVE.point(
        x_coordinate=0x72D867F93A93AC27DF9FF01AFFE74885C8C540420,
        y_coordinate=0x0224A9C3947852B97C5599D5F4AB81122ADC3FD9B,
    ),
)
"""DSTU 4145-2002 example curve from Annex B (m = 163, pentanomial basis)."""


__all__: Final[list[str]] = [
    "Dstu4145DomainParameters",
    "DSTU4145_M163_PB",
]
